### PR TITLE
Add collapsible segment editor widget to Slicer extension

### PR DESCRIPTION
**Pull request by jlvahldiek**
- added collapsible qMRMLSegmentEditorWidget below "active learning" section
- default status is collapsed
- removed now unnecessary user setting auto-open segment editor 

(see also discussion in PR #567)

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
It has merge conflicts.. please resolve the same.. I will verify the UI once and it shall be good to merge with main branch..

**Comment by jlvahldiek** [comment]
> It has merge conflicts.. please resolve the same.. I will verify the UI once and it shall be good to merge with main branch..

Should be fixed now. Thanks.

**Review by SachidanandAlle — APPROVED** [review]
Looks Good

**Comment by SachidanandAlle** [comment]
Thanks for the contributions and making it better :)

**Pull request merged**
