### PR TITLE
[WIP] Adding support for user-scribbles based post processing methods

### PR DESCRIPTION
**Pull request by masadcv**
I am adding this pull request as I just went through merging the changes with latest main and want to save you guys from the pain of doing it again :smile: 

This pull request extends support for new features, and hence there are no breaking changes.

Specifically, in this the following features have been added:
- Adding endpoint for postprocessing methods in `monailabel/endpoints/postproc.py`
- Adding interface for postprocessing methods in `monailabel/interfaces/app.py`
- Adding task for postprocessing methods in `monailabel/interfaces/tasks/postproc.py`
- Adding post processing transforms to implement CRF-based post processing in `monailabel/utils/others/post.py`
- Adding a sample app demonstrating the new features in `sample-apps/segmentation_spleen_postproc/`
- Added GUI elements and logic to the Slicer extension for enabling scribbles-based update

I would appreciate if we can review this and update the code for adding to the project. I will be happy to incorporate the suggestions/comments. I have also allowed edits so feel free to change anything.

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
@diazandr3s lets discuss if we want to add this feature as part of 0.1 version in our next product meeting...

**Comment by SachidanandAlle** [comment]
lets fix little bit on optimizing (avoid duplication) the code..  let's mark the PR as WIP..

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/compare/scribbles

This shall be the optimized way of implementing scribbles.. 
Ideally user should be able to add all code in their corresponding app.. the current monailabel framework should be enough to support any api calls... etc..  as we discussed earlier.. current infer task should be enough if it can support passing label along with additional params/image..

However scribbles need additional inputs/iteractions from client.. so that shall be ok and seperate discussion to have... we can decide how to keep client (3d slicer) and monilabel server seperate in future..

however currently things (wrt user experience etc.. ) are not promising to merge this feature into main repo.. created a seperate branch.. so you can work on this branch.. 

when we reach the best experience to add this feature by-default in monai label, we can merge this branch (with slicer changes)

For now I don't recommend to merge this PR to main branch.. as we are tring to bring in changes in 3D slicer as part of the support.. 

lets have a seperate discussion on this with other stakeholders for 0.1 release..

**Comment by diazandr3s** [comment]
Let's discuss this in more detail in our Monday meeting.

**Comment by masadcv** [comment]
@diazandr3s Can we arrange a meeting to discuss this in detail? Perhaps this one may be for the Wednesday MONAILabel meeting?

@SachidanandAlle Lets discuss the requirements in detail when we have the chance so I can convey to you what needs to be supported in order to have the endpoints and server interfaces that can allow us to implement scribbles applications. The reason I opened this pull request was to give you updated code and hence save you guys time re-implementing the wheel. Please do have a closer look at the postproc endpoint as that primarily covers most of our requirements at the moment.

**Pull request closed without merging**
