### PR TITLE
Add basic auth with roles [admin, reviewer, annotator, user]

### PR DESCRIPTION
**Pull request by SachidanandAlle**
Signed-off-by: SACHIDANAND ALLE <sachidanand.alle@gmail.com>

This shall be only the first draft.. that can support following 4 different scopes/roles/access management
- admin (can do everything)
- reviewer (admin minus can not delete images; however can delete saved labels)
- annotator ( reviewer minus cannot delete labels)
- user (can only run basic inference and related activities without submitting/modifying anything back in server)

By default the feature is disabled, and you can enable it by running
`export MONAI_LABEL_AUTH_ENABLE=True`

and then start monailabel server.

In the next draft, we can have corresponding changes in 3D slicer/client plugins

### CODE REVIEW

**Review by diazandr3s — APPROVED** [review]
This looks good to me ... It's great to have the first draft of what many users have requested - GCP is one of the users that will greatly benefit from this

**Comment by lassoan** [comment]
> In the next draft, we can have corresponding changes in 3D slicer/client plugins

3D Slicer allows viewing/editing/saving user information (full name, email, etc), which may be useful for identification of the user. There is a user information widget that you can pop in a dialog or embed into your module GUI.

**Comment by kbressem** [comment]
> > In the next draft, we can have corresponding changes in 3D slicer/client plugins
> 
> 3D Slicer allows viewing/editing/saving user information (full name, email, etc), which may be useful for identification of the user. There is a user information widget that you can pop in a dialog or embed into your module GUI.

Has there been a follow up PR where this was implemented?

**Comment by sowwnn** [comment]
Is there any documentation on how to install roles? I really want to use this function but I don't know how to install it.

**Pull request merged**
