### PR TITLE
Dep version upgrade

### PR DESCRIPTION
**Pull request by SachidanandAlle**
- upgrade dependencies
- Fix if check for numpy array

### CODE REVIEW

**Review by tangy5 — APPROVED** [review]

**Comment by YanxuanLiu** [comment]
Hi @SachidanandAlle, 
Should we ignore the vulnerability? It's better to fix it if the component is a direct dependence.

**Comment by SachidanandAlle** [comment]
They are again from the plugin folder.. I have mentioned earlier.. we need to discard plugin folder from the scan..

**Comment by pxLi** [comment]
> They are again from the plugin folder.. I have mentioned earlier.. we need to discard plugin folder from the scan..

Again, we are not allowed to do so. 
For now we can only fix vuls of direct dependencies, or add exceptions in internal allow list if indirect dependencies.

**Comment by SachidanandAlle** [comment]
I have no solution for this.. we are looking for exceptions here.. or we have to remove the plugins from this repository

**Comment by SachidanandAlle** [comment]
They are picking these dependencies from QuPath and OHIF base project (external) files.. and we don't control them.. they are other 3rd party oos projects

**Comment by pxLi** [comment]
> I have no solution for this.. we are looking for exceptions here.. or we have to remove the plugins from this repository

We have the options to whitelist those, 
the point here is that please help determine if it could be fixed or its actually a indirect dep, 
so we could take actions but not just ignore those, thanks~

**Comment by pxLi** [comment]
I have added this one to whitelist as its a thirdparty dep and we cannot fix from our-side to unblock CI

**Pull request merged**
