### PR TITLE
[WIP] Add misc Apps

### PR DESCRIPTION
**Pull request by diazandr3s**
Signed-off-by: Andres <diazandr3s@gmail.com>

- Create a branch for several multilabel Apps: Vertebra segmentation, teeth segmentation, lesion sclerosis segmentation, etc.
This replaces the [PR](https://github.com/Project-MONAI/MONAILabel/pull/588)/branch

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
This PR is for tracking only.. to pull the changes from MAIN branch.

**Review by SachidanandAlle — CHANGES_REQUESTED** [review]
This PR is for tracking only

**Comment by SachidanandAlle** [comment]
may be we can close this PR

**Comment by diazandr3s** [comment]
> may be we can close this PR

Agree. Let's keep the branch for a bit more though ... we may need something there

**Pull request closed without merging**
