### PR TITLE
Add spacing & image size args in TTA

### PR DESCRIPTION
**Pull request by diazandr3s**
Signed-off-by: Andres <diazandr3s@gmail.com>

- Add spacing and image size as arguments in TTA scoring

### CODE REVIEW

**Review by SachidanandAlle — APPROVED** [review]

**Review by SachidanandAlle — CHANGES_REQUESTED** [review]
lets wait for other PR to get merged

**Comment by diazandr3s** [comment]
> lets wait for other PR to get merged

Ready?

**Review by SachidanandAlle — APPROVED** [review]

**Comment by SachidanandAlle** [comment]
can you please raise a new PR for this fix.. that might be easier than resolving conflicts

**Comment by diazandr3s** [comment]
Closing PR - new PR created with these changes https://github.com/Project-MONAI/MONAILabel/pull/357

**Pull request closed without merging**
