### PR TITLE
Support monai 0.6 interation

### PR DESCRIPTION
**Pull request by SachidanandAlle**
Signed-off-by: Sachidanand Alle <salle@nvidia.com>

Changes are done based on current monai main/dev branch
> Build will fail as there is no pip package available for monai dev branch

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/issues/152

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAI/pull/2539

**Comment by SachidanandAlle** [comment]
Too many apps at the end to verify.. :(

**Comment by diazandr3s** [comment]
> Too many apps at the end to fix and verify.. :(

I just checkout this branch and inference works great, However, I got this error when training DeepEdit spleen App:


>     d[self.guidance] = self._apply(guidance, discrepancy)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/apps/deepgrow/transforms.py", line 386, in _apply
>     g[0].append([-1] * len(neg))
> AttributeError: 'Tensor' object has no attribute 'append'
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 89, in <module>
>     run_main()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 74, in run_main
>     result = a.train(request)
>   File "/home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/main.py", line 102, in train
>     return task()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 217, in __call__
>     self.trainer().run()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/trainer.py", line 56, in run
>     super().run()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/workflow.py", line 242, in run
>     super().run(data=self.data_loader, max_epochs=self.state.max_epochs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 701, in run
>     return self._internal_run()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 774, in _internal_run
>     self._handle_exception(e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
>     self._fire_event(Events.EXCEPTION_RAISED, e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
>     func(*first, *(event_args + others), **kwargs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/handlers/stats_handler.py", line 148, in exception_raised
>     raise e
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 744, in _internal_run
>     time_taken = self._run_once_on_dataset()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 848, in _run_once_on_dataset
>     self._handle_exception(e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
>     self._fire_event(Events.EXCEPTION_RAISED, e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
>     func(*first, *(event_args + others), **kwargs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/handlers/stats_handler.py", line 148, in exception_raised
>     raise e
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
>     self.state.output = self._process_function(self, self.state.batch)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/apps/deepgrow/interaction.py", line 77, in __call__
>     batchdata = self.transforms(batchdata)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/transforms/compose.py", line 159, in __call__
>     input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/transforms/transform.py", line 108, in apply_transform
>     raise RuntimeError(f"applying transform {transform}") from e
> RuntimeError: applying transform <monai.apps.deepgrow.transforms.AddRandomGuidanced object at 0x7f6d8ad0f0b8>

**Comment by diazandr3s** [comment]
> > Too many apps at the end to fix and verify.. :(
> 
> I just checkout this branch and inference works great, However, I got this error when training DeepEdit spleen App:
> 
> > ```
> > d[self.guidance] = self._apply(guidance, discrepancy)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/apps/deepgrow/transforms.py", line 386, in _apply
> > g[0].append([-1] * len(neg))
> > AttributeError: 'Tensor' object has no attribute 'append'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 89, in 
> > run_main()
> > File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 74, in run_main
> > result = a.train(request)
> > File "/home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/main.py", line 102, in train
> > return task()
> > File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 217, in **call**
> > self.trainer().run()
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/trainer.py", line 56, in run
> > super().run()
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/workflow.py", line 242, in run
> > super().run(data=self.data_loader, max_epochs=self.state.max_epochs)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 701, in run
> > return self._internal_run()
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 774, in _internal_run
> > self._handle_exception(e)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
> > self._fire_event(Events.EXCEPTION_RAISED, e)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
> > func(*first, *(event_args + others), **kwargs)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/handlers/stats_handler.py", line 148, in exception_raised
> > raise e
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 744, in _internal_run
> > time_taken = self._run_once_on_dataset()
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 848, in _run_once_on_dataset
> > self._handle_exception(e)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
> > self._fire_event(Events.EXCEPTION_RAISED, e)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
> > func(*first, *(event_args + others), **kwargs)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/handlers/stats_handler.py", line 148, in exception_raised
> > raise e
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
> > self.state.output = self._process_function(self, self.state.batch)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/apps/deepgrow/interaction.py", line 77, in **call**
> > batchdata = self.transforms(batchdata)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/transforms/compose.py", line 159, in **call**
> > input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items)
> > File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/transforms/transform.py", line 108, in apply_transform
> > raise RuntimeError(f"applying transform {transform}") from e
> > RuntimeError: applying transform <monai.apps.deepgrow.transforms.AddRandomGuidanced object at 0x7f6d8ad0f0b8>

I've got this error because I was using the previous version of MONAI. Now it is working for both inference and training!!
The thing I see now is that the logs changed. Now it doesn't show the progress per batch:

> [2021-07-07 10:28:46,882] [INFO] (monailabel.utils.train.basic_train) - Total Records for Training: 26
> [2021-07-07 10:28:46,882] [INFO] (monailabel.utils.train.basic_train) - Total Records for Validation: 6
> [2021-07-07 10:28:47,852] [INFO] (monailabel.utils.train.basic_train) - Adding Validation Handler to run every '1' interval
> [2021-07-07 10:28:47,852] [INFO] (monailabel.utils.train.basic_train) - Load Path /home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/model/model_01/model.pt
> [2021-07-07 10:28:47,853] [INFO] (ignite.engine.engine.SupervisedTrainer) - Engine run resuming from iteration 0, epoch 0 until 50 epochs
> [2021-07-07 10:28:47,893] [INFO] (ignite.engine.engine.SupervisedTrainer) - Restored all variables from /home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/model/model_01/model.pt
> ignoring non-scalar output in StatsHandler, make sure `output_transform(engine.state.output)` returns a scalar or a dictionary of key and scalar pairs to avoid this warning. <class 'list'>
> ignoring non-scalar output in TensorBoardStatsHandler, make sure `output_transform(engine.state.output)` returns a scalar or a dictionary of key and scalar pairs to avoid this warning. <class 'list'>
> [2021-07-07 10:32:52,090] [INFO] (ignite.engine.engine.SupervisedTrainer) - Got new best metric of train_dice: 0.06871502846479416
> [2021-07-07 10:32:52,090] [INFO] (ignite.engine.engine.SupervisedTrainer) - Current learning rate: 0.0001
> [2021-07-07 10:32:52,090] [INFO] (ignite.engine.engine.SupervisedTrainer) - Epoch[1] Metrics -- train_dice: 0.0687
> [2021-07-07 10:32:52,090] [INFO] (ignite.engine.engine.SupervisedTrainer) - Key metric: train_dice best value: 0.06871502846479416 at epoch: 1
> [2021-07-07 10:32:52,186] [INFO] (ignite.engine.engine.SupervisedEvaluator) - Engine run resuming from iteration 0, epoch 0 until 1 epochs
> [2021-07-07 10:33:25,607] [INFO] (ignite.engine.engine.SupervisedEvaluator) - Got new best metric of val_mean_dice: 0.12732452154159546
> [2021-07-07 10:33:25,607] [INFO] (ignite.engine.engine.SupervisedEvaluator) - Epoch[1] Metrics -- val_mean_dice: 0.1273
> [2021-07-07 10:33:25,607] [INFO] (ignite.engine.engine.SupervisedEvaluator) - Key metric: val_mean_dice best value: 0.12732452154159546 at epoch: 1
> [2021-07-07 10:33:25,730] [INFO] (monailabel.utils.train.basic_train) - New Model published: /home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/model/model_01/model.pt => /home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/model/model.pt
> [2021-07-07 10:33:25,730] [INFO] (ignite.engine.engine.SupervisedEvaluator) - Epoch[1] Complete. Time taken: 00:00:34
> [2021-07-07 10:33:25,730] [INFO] (ignite.engine.engine.SupervisedEvaluator) - Engine run complete. Time taken: 00:00:34
> [2021-07-07 10:33:25,731] [INFO] (ignite.engine.engine.SupervisedTrainer) - Epoch[1] Complete. Time taken: 00:04:38
>

**Review by diazandr3s — APPROVED** [review]

**Pull request merged**
