### PR TITLE
Add score field for labels in datastore

### PR DESCRIPTION
**Pull request by aihsani**
- [x] Added score fields (one or more scores possible) for each label in datastore
- [x] Updated label fields with new `id` and `path` fields. `id` is to be used by the user app, whereas `path` is for MONAI Label components to use
- [ ] Discuss client updates to allow for automated segmentation

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
I will help on resolving conflicts for this branch

**Comment by aihsani** [comment]
The new changes are not backward compatible. They will result in a `dataset.json` that looks like this:
```json
{
  "name": "new-dataset",
  "description": "New Dataset",
  "objects": [
    {
      "image": {
        "id": "la_011.nii.gz",
        "access_timestamp": null
      },
      "labels": null
    },
    {
      "image": {
        "id": "la_029.nii.gz",
        "access_timestamp": null
      },
      "labels": {
        "original": null,
        "updated": {
          "id": "la_029/updated.nii.gz",
          "access_timestamp": "2021-05-10 22:17:42.592049",
          "scores": null
        }
      }
    },
...
}
```
and a file structure like this
```
.
├── dataset.json
├── la_003
│   └── updated.nii.gz
├── la_003.nii.gz
├── la_004.nii.gz
├── la_005
│   └── updated.nii.gz
├── la_005.nii.gz
├── la_007.nii.gz
├── la_009.nii.gz
├── la_010.nii.gz
├── la_011.nii.gz
├── la_014.nii.gz
├── la_016.nii.gz
├── la_017.nii.gz
├── la_018
│   └── updated.nii.gz
├── la_018.nii.gz
├── la_019.nii.gz
├── la_020.nii.gz
├── la_021.nii.gz
├── la_022.nii.gz
├── la_023.nii.gz
├── la_024.nii.gz
├── la_026.nii.gz
├── la_029
│   └── updated.nii.gz
├── la_029.nii.gz
└── la_030.nii.gz
```

`updated` files are labels saved by the user after corrections to the originally generated label `original` via automatic segmentation

**Comment by SachidanandAlle** [comment]
Looks good.. but how about avoiding creating directory per label while saving the label..  we can still have tag as part of label id/filename..

**Comment by SachidanandAlle** [comment]
To avid confusion.. I am closign this PR...

**Pull request closed without merging**
