### PR TITLE
Filewatcher limit fix + datastore interface update

### LINKED ISSUE #82: inotify watch limit reached
**Describe the bug**
Not sure what exactly generated the error, but it happened when I added new images in the datastore folder while the server was running. Now I can't start the server again

**To Reproduce**
2. Install '....'
3. Run commands '....'

**Expected behavior**

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**

  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "main.py", line 52, in startup_event
    get_app_instance()
  File "/home/adp20local/Documents/MONAILabel/monailabel/utils/others/generic.py", line 89, in get_app_instance
    return app_instance(settings.APP_DIR, settings.STUDIES)
  File "/home/adp20local/Documents/MONAILabel/monailabel/utils/others/app_utils.py", line 32, in app_instance
    o = c(app_dir=app_dir, studies=studies)
  File "/home/adp20local/Documents/MONAILabel/sample-apps/deepedit_heart/main.py", line 73, in __init__
    resources=None,
  File "/home/adp20local/Documents/MONAILabel/monailabel/interfaces/app.py", line 42, in __init__
    self._datastore: Datastore = LocalDatastore(studies)
  File "/home/adp20local/Documents/MONAILabel/monailabel/utils/datastore/local.py", line 110, in __init__
    self._observer.start()
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/api.py", line 256, in start
    emitter.start()
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 199, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 396, in _add_dir_watch
    self._add_watch(path, mask)
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 417, in _add_watch
    Inotify._raise_error()
  File "/home/adp20local/anaconda3/envs/monai_env/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 429, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached

[2021-05-21 16:27:20,183] [ERROR] (uvicorn.error) - Application startup failed. Exiting.

### PR DESCRIPTION
**Pull request by aihsani**
- Filewatcher limit fix #82 
- API to get label based on image and tag #85

### CODE REVIEW

**Comment by aihsani** [comment]
Id' say yes because that's the return spec but I can update

**Comment by aihsani** [comment]
Updated to return only the value

**Comment by SachidanandAlle** [comment]
I guess you forgot to run ci check on local box... 

https://github.com/Project-MONAI/MONAILabel/runs/2670046070

**Comment by aihsani** [comment]
I did not. It doesn't want to pass it no matter what I do. I did autofix and manual fix

**Comment by aihsani** [comment]
Doesn't work

**Pull request merged**
