### PR TITLE
BUG: Added missing ImageDataStatistics to slicer MONAILabelReviewer plugin

### PR DESCRIPTION
**Pull request by fbordignon**
This file was missing preventing the plugin from loading when compiling it as an extension.

### CODE REVIEW

**Comment by tangy5** [comment]
Thanks. You could add "-s" (sing-off) in the git commit command to pass the DCO check.

**Review by SachidanandAlle — COMMENTED** [review]
Looks like there is Tab character in the beginning of new line..

**Comment by fbordignon** [comment]
> Looks like there is Tab character in the beginning of new line..

You mean at the newline I've added with the commit or the at the commit message? I don't see it.

**Comment by SachidanandAlle** [comment]
> > Looks like there is Tab character in the beginning of new line..
> 
> You mean at the newline I've added with the commit or the at the commit message? I don't see it.

Please ignore.. the github on mobile app shows this weird extra indent..

Thanks for the fix

**Pull request merged**
