### PR TITLE
DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by sedghi**
Migrating the Monai Label plugin for the upcoming OHIF 3.9 and Cornerstone3D 2.0 to observe the migration process and take notes. 

The AutoSegmentation works, but I doubt there's much left to do for the rest of it to function properly.

### CODE REVIEW

**Comment by tangy5** [comment]
I can continue to work on making other part compatible to OHIF3.9. Looks like there will be bigger changes to switch 3.9 from 3.8. 
Will check one by one. 

Thanks again for the guide.

**Comment by sedghi** [comment]
@tangy5 Yes, it's a significant change since Cornerstone3D 2.0 was released. It won't happen very often.
https://www.cornerstonejs.org/docs/migration-guides/intro

**Comment by SachidanandAlle** [comment]
Let me work on this one time.  I will take care from here.  @sedghi you can help to review it once I submit the PR

**Comment by SachidanandAlle** [comment]
WIP: https://github.com/Project-MONAI/MONAILabel/tree/sachi/ohifv3

**Comment by tangy5** [comment]
> WIP: https://github.com/Project-MONAI/MONAILabel/tree/sachi/ohifv3
> 
> This should take care of most of the things. So far verified
> 
> 1. basic auto segmentation
> 2. point prompts (deepgrow/deepedit/vista3d/sam2 models)
> 3. class prompts (seg/vista models)
> 
> Need to add back new other things like Active Learning..

Great, after this is finished, I will add VISTA3D supports to OHIF 3.9. 
Thanks again.

**Comment by sedghi** [comment]
@SachidanandAlle yes, let me know when to review

**Comment by SachidanandAlle** [comment]
> @SachidanandAlle, consider merging a formatting PR first to reduce the noise from numerous formatting fixes.

https://github.com/Project-MONAI/MONAILabel/pull/1784

**Comment by sedghi** [comment]
@SachidanandAlle Does your PR have my changes here? shall we close this one?

**Comment by SachidanandAlle** [comment]
Yes.. I have cherry picked the needed ones to support ohif latest.  During this I might have missed something.

**Comment by sedghi** [comment]
Let's close this one, and I'll work on that one.

**Comment by SachidanandAlle** [comment]
Thanks :)

**Pull request closed without merging**
