### PR TITLE
Fix md5 hashing with FIPS mode

### PR DESCRIPTION
**Pull request by MattTheCuber**
MD5 hashing is not allowed in FIPS enabled machines for security. A simple fix is to use the `usedforsecurity=False` flag in the `md5()` calls.

### CODE REVIEW

**Review by SachidanandAlle — COMMENTED** [review]
You can simply add a wrapper function in the utility class and use the same.. that will avoid writing same if-else condition too many times.. code/changes will look simpler

**Comment by MattTheCuber** [comment]
> You can simply add a wrapper function in the utility class and use the same.. that will avoid writing same if-else condition too many times.. code/changes will look simpler

Do you mean in https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/utils/others/class_utils.py?

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/utils/others/generic.py

```python
def md5_digest(s:str) -> str:
    if sys.version_info.minor < 9:
        return hashlib.md5(s.encode("utf-8")).hexdigest()
    return hashlib.md5(s.encode("utf-8"), usedforsecurity=False).hexdigest()
```

**Comment by MattTheCuber** [comment]
Done. _thanks git..._

**Review by SachidanandAlle — APPROVED** [review]

**Pull request merged**
