### PR TITLE
[DO NOT REVIEW] Test Pre-merge pipeline [skip ci]

### PR DESCRIPTION
**Pull request by YanxuanLiu**
This PR is to test pre-merge only

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
is this done? ready to merge?

**Comment by YanxuanLiu** [comment]
This PR is for testing blossom pre-merge pipeline.
The initialization of blossom cicd pipeline is blocked by vulnerability scan failure, blossom team is still working on that.
Once pre-merge pipeline is ready, I will close the PR.

**Comment by pxLi** [comment]
build

**Comment by SachidanandAlle** [comment]
i see the scan tool trying to report dependency related issues from plugins folder.. (we excluded it earlier with a valid reason as they are not own by monailabel by design. the dependencies are coming from core applications like qupath, ohif and we don't have any control on that)

hence, i do recommend to exclude https://github.com/Project-MONAI/MONAILabel/tree/main/plugins from scanning

**Comment by pxLi** [comment]
> i see the scan tool trying to report dependency related issues from plugins folder.. (we excluded it earlier with a valid reason as they are not own by monailabel by design. the dependencies are coming from core applications like qupath, ohif and we don't have any control on that)
> 
> hence, i do recommend to exclude https://github.com/Project-MONAI/MONAILabel/tree/main/plugins from scanning

We would like that too, but per security team, currently we (open-source projects) are allowed to modify exclude dirs.
For now, the only thing we can do is that either fix the vuls or add vuls to exception list

**Comment by SachidanandAlle** [comment]
we have already taken the exception for this earlier.. to exclude

**Comment by pxLi** [comment]
> 

these are from different places. 

pre-merge scan (provided by blossom) does not share the same config as nspec.

But yes, we could ask them to make sure things are consistent, but this depends on their plan

**Pull request closed without merging**
