### PR TITLE
update 2 package dependencies

### PR DESCRIPTION
**Pull request by tangy5**
multipart 0.0.9
fastapi==0.110.0

### CODE REVIEW

**Comment by tangy5** [comment]
Hi @SachidanandAlle , can you help tag a MONAILabel 0.8.1 version to enable the new monaitoolkit release, thank you! 
:)

**Comment by tangy5** [comment]
We are getting an error from packaging dicom-client GCP, @SachidanandAlle , do you have any idea? 

```
  File "/home/runner/work/MONAILabel/MONAILabel/monailabel/app.py", line 23, in <module>
    from monailabel.endpoints import (
  File "/home/runner/work/MONAILabel/MONAILabel/monailabel/endpoints/activelearning.py", line 20, in <module>
    from monailabel.interfaces.app import MONAILabelApp
  File "/home/runner/work/MONAILabel/MONAILabel/monailabel/interfaces/app.py", line 31, in <module>
    from dicomweb_client.ext.gcp.session_utils import create_session_from_gcp_credentials
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dicomweb_client/ext/gcp/session_utils.py", line 8, in <module>
    raise ImportError(
ImportError: The `dicomweb-client` package needs to be installed with the "gcp" extra requirements to use this module, as follows: `pip install dicomweb-client[gcp]`
```

**Review by SachidanandAlle — APPROVED** [review]

**Comment by SachidanandAlle** [comment]
Check locally on a new pip venv to debug the dependency issue

**Comment by SachidanandAlle** [comment]
can you resolve conflicts and try again.. 

add your changes to both requirements.txt and 
https://github.com/Project-MONAI/MONAILabel/blob/main/setup.cfg#L37-L70

**Comment by SachidanandAlle** [comment]
`0.8.2rc1` will be created and pushed.. @tangy5 u can test and verify all is ok.. and then we can push the final tag for `0.8.2`
https://github.com/Project-MONAI/MONAILabel/actions/runs/8528081530

**Pull request merged**
