### PR TITLE
NuClick Training & Inference Pipeline Updates

### PR DESCRIPTION
**Pull request by finalelement**
Based on the latest integration of NuClick Transform Components, the NuClick Training & Inferencing pipeline needs to be updated

Signed-off-by: vnath <vnath@nvidia.com>

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
also some transform moved to monai core for infer.. same can be used in corresponding infer task for nuclick

**Comment by SachidanandAlle** [comment]
And you can fix the pre-commit by running

https://github.com/Project-MONAI/MONAILabel/blob/main/CONTRIBUTING.md
`python -m pip install pre-commit`
`python -m pre_commit run --all-files`

**Comment by finalelement** [comment]
@SachidanandAlle What do you mean by some transform moved to MONAI Core for infer?

Thanks for the pre-commit heads up. I made changes for the infer in nuclick.

**Comment by finalelement** [comment]
@SachidanandAlle I did basic training test of NuClick, please test once at your end. Let me know if more changes are needed.

**Review by SachidanandAlle — APPROVED** [review]

**Pull request merged**
