### PR TITLE
feat: Allow networks to be loaded on CPU if CUDA is not available

### PR DESCRIPTION
**Pull request by swederik**
Hi everyone,

I wanted to try MONAI Label on my laptop but it does not have a GPU with CUDA. It's not fast, but it seems to work. I only changed it for inference right now, but I see torch.load and torch.jit.load in the epistemic.py and tta.py inside tasks/scoring as well.

I don't have an NVIDIA GPU around to check if this breaks anything for anyone else though.

Thoughts?

### CODE REVIEW

**Review by SachidanandAlle — APPROVED** [review]

**Comment by SachidanandAlle** [comment]
The CI Build will take care of basic functionalities on CUDA.. the code changes looks ok to me.. it should not break anything on GPUs.. if these checks help you/user to run basic inference on CPU.. then why not.. 

we can merge the PR once all the build checks are passed..
Thanks for your contributions

**Comment by SachidanandAlle** [comment]
The static check fails.. can you please run 

```
./runtests.sh --codeformat # this will fail when there are any errors..
./runtests.sh --autofix # This is do codeformat fixes
```
To run the unit tests locally..
```./runtests.sh --unittests```

https://github.com/Project-MONAI/MONAILabel/blob/main/CONTRIBUTING.md#the-contribution-process

**Comment by markus-hinsche** [comment]
@swederik Awesome work! This is very helpful for my team. Would be soo nice if this gets merged. 
Let me know if you need help with the tests and code formatting

**Comment by SachidanandAlle** [comment]
on behalf.. let me fix the build for now.. once it's merged.. you can update your existing monailabel based on github to try..

**Comment by SachidanandAlle** [comment]
Merged the PR.. thank you for contributing to MONAI Label

**Comment by swederik** [comment]
Thanks so much @SachidanandAlle, I haven't had a chance to get back to this lately.

**Pull request merged**
